// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iryafwncdeknceznkoff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeWFmd25jZGVrbmNlem5rb2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTc3NTIsImV4cCI6MjA3MjgzMzc1Mn0.C0gJ9RMDBKJGTQ6EONqJa6IdH6p8uvAFMWEi7EYXe5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});